### ISSUE TITLE
Drag / drop IR also creates IV ????

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#222]
There is a bug somewhere because if you simply drag / drop a single ir spectrum the IV tab is also created.

[ir.jdx.zip](https://github.com/zakodium-oss/analysis-ui-components/files/9627812/ir.jdx.zip)

![image](https://user-images.githubusercontent.com/1484241/191805626-e3b3ffb9-bfdd-4a08-a115-ff53e27103d5.png)

**Comment by santimirandarp** [comment]
Because it is an "IV" it comes from the biologic-parser, I commented it out from [this line](https://github.com/zakodium-oss/analysis-ui-components/blob/fd84fabf6402ea4028ea9b1893c3a35a31828e10/src/app/context/load.ts#L12) and the problem disappears. 

I think this could actually be an error in the parser, I am not sure yet, but because of this line:
```
export async function convert(fileList: PartialFileList): Promise<BioLogic[]> {
  const dirs = groupFiles(fileList);
  let results: BioLogic[] = [];

  /* can not use `forEach` and pass `async` functions */
  for (const dir of dirs) {
    let result: BioLogic = {};
    result.dir = dir.key;
```

It may return a result even when it does not parse anything, something like this:
```
[{dir:"..."}, {dir:"..."}]
```

**Comment by lpatiny** [comment]
Ok thanks for the analysis. I think you could fix the parser so that if there is nothing the array is empty. We can quickly make a release of the biologic parser to fix this issue.

**Comment by santimirandarp** [comment]
I think this issue was closed at [biologic-parser](https://github.com/cheminfo/biologic-converter/commit/71506d1ecfdd9bfff5a474356c6ed6c2c8b59a6f)

**Comment by targos** [comment]
Fixed
